### ISSUE TITLE
USB C power

### ISSUE THREAD

**Issue by mr4lexndr** [will127534/CM4-Nvme-NAS#2]
Hi, as I understand a 12V dc jack powers the board. are you planning to use USB C as a power source? It would be a great feature for me.

**Comment by will127534** [comment]
Nope, USB-C is for the on-board Pico.
The entire board loaded with NVMe needs USB-PD for higher power, so even if I added USB-C power source I think there will be issues where people plugged it in a 5V only charger.

You can use a USB-C to DC Jack cable with 12V PD, this is actually my current configuration.
