### ISSUE TITLE
+/- of PCIe RX and TX differential pairs flipped?

### ISSUE THREAD

**Issue by dumtux** [will127534/CM4-Nvme-NAS#5]
Looking at your schematics, I found interesting flipped differential pair connection. `TX` and `RX` are flipped to M.2 M connector. But `CLK` is not flipped. Could you explain why?
(It's same for all four M.2 connectors.)

### Flipped `TX` and `RX`

| ASM1184        |  M.2 M conn 1   |
| -------------- | ---------------- |
| `PCIe_TX_N_1`  |  (49) `PETp0`    |
| `PCIe_TX_P_1`  |  (47) `PETn0`    |
| `PCIe_RX_N_1`  |  (43) `PERp0`    |
| `PCIe_RX_P_1`  |  (41) `PERn0`    |

### Not-flipped `CLK`

| ASM1184        |  M.2 M conn 1   |
| -------------- | ---------------- |
| `PCIe_CLK_P_1` |  (55) `REFCLKp`  |
| `PCIe_CLK_N_1` |  (53) `REFCLKn`  |

**Comment by dumtux** [comment]
I found that PCIe is diff pair polarity agnostic.
Further reading: https://www.teledynelecroy.com/doc/understanding-lane-reversal-and-polarity

**Comment by prasimix** [comment]
Maybe it would be a good idea to correct the p0 / B- and n0 / B+ markings?
![Image](https://github.com/user-attachments/assets/4f8bec46-32a3-4036-8510-18f50ee414ba)

**Comment by will127534** [comment]
> Maybe it would be a good idea to correct the p0 / B- and n0 / B+ markings? ![Image](https://github.com/user-attachments/assets/4f8bec46-32a3-4036-8510-18f50ee414ba)

No, please follow the M.2 connector spec
